In [1]:
import gym

A cart that tries to balance and keep a stick upright. Reward is accumulated for every time step as +1, so a larger reward will result from keeping the stick upright longer

In [2]:
e = gym.make('CartPole-v0')

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [3]:
obs = e.reset()

In [4]:
obs

array([-0.015828  , -0.01025452, -0.01278763, -0.04506633])

Four observations are the x-coordinate of the stick's center of mass, its speed, angle to the platform and angular speed

But the system doesn't know this, so it has to learn to interpret these numbers by itself

In [5]:
e.action_space

Discrete(2)

`action_space` is of the Discrete type, so 0 platform left or 1 platform right

In [6]:
e.observation_space

Box(4,)

This means vector of size four with values of [-inf, inf]

In [7]:
e.step(0)

(array([-0.01603309, -0.20519079, -0.01368896,  0.24355471]), 1.0, False, {})

Here pushed platform to left (ie arg of 0)

reward of 1, done flag is False so the episode is not over yet

In [8]:
e.action_space.sample()

0

In [9]:
e.action_space.sample()

1

In [10]:
e.observation_space.sample()

array([ 2.0658181e+00,  6.9937125e+37,  3.7601247e-02, -5.1957849e+37],
      dtype=float32)

In [11]:
e.observation_space.sample()

array([ 1.4005835e+00, -4.2475939e+37,  3.2821098e-01,  3.1555251e+38],
      dtype=float32)

Here used `sample()` of `Space` on action_space and observation_space.  

Returns a random sample from the underlying space, which in the discrete action space means 0 or 1. 

This can be used when we're not sure how to perform an action

Observation space is a random vector of four numbers, so not that useful